### ISSUE TITLE
Implement paging for calendar list

### ISSUE THREAD

**Issue by Thomas9693** [Thomas9693/webcalendar#10]

**Comment by Thomas9693** [comment]
Kannst du das noch in schön machen! :+1: 

ist im div "div_event_list" und id ist "list_range_select"

**Comment by TTDennis** [comment]
Wenn man im List view mode ist und dann aktualisiert lädt der irgendwie keine Einträge rein. Nur wenn man von month oder week kommt oder so

**Comment by Thomas9693** [comment]
Meinst du aktualisieren über den Browser?

----- Ursprüngliche Nachricht -----
Von: "TTDennis" <notifications@github.com>
Gesendet: ‎16.‎02.‎2015 20:24
An: "Thomas9693/webcalendar" <webcalendar@noreply.github.com>
Cc: "Thomas9693" <thomas9693@gmail.com>
Betreff: Re: [webcalendar] Implement paging for calendar list (#10)

Wenn man im List view mode ist und dann aktualisiert lädt der irgendwie keine Einträge rein. Nur wenn man von month oder week kommt oder so

**Comment by Thomas9693** [comment]
Hab eben nochmal alles durchgetestet... Bei mir funktioniert alles....

**Comment by Thomas9693** [comment]
Fixed
