### ISSUE TITLE
Neues Event -> Kategorie hinzufügen

### ISSUE THREAD

**Issue by Thomas9693** [Thomas9693/webcalendar#2]
Neu erstelltes Event öffnet nicht automatisch wieder um Kategorien hinzuzufügen

**Comment by TTDennis** [comment]
Kannst du mir dazu nach dem erstellen von einem Event die ID zurück geben? Sonst geht das gar nicht, weil ich ja nicht "weiß" welches event ich automatisch öffnen muss.

**Comment by Thomas9693** [comment]
Ich versuch des einzubauen. Wenn ich den Success bekomme soll er es öffnen.

----- Ursprüngliche Nachricht -----
Von: "TTDennis" <notifications@github.com>
Gesendet: ‎15.‎02.‎2015 15:38
An: "Thomas9693/webcalendar" <webcalendar@noreply.github.com>
Cc: "Thomas9693" <thomas9693@gmail.com>
Betreff: Re: [webcalendar] Neues Event -> Kategorie hinzufügen (#2)

Kannst du mir dazu nach dem erstellen von einem Event die ID zurück geben? Sonst geht das gar nicht, weil ich ja nicht "weiß" welches event ich automatisch öffnen muss.

**Comment by Thomas9693** [comment]
Erledigt! :+1:
