### ISSUE TITLE
Events über mehrer Wochen werden nicht korrekt angezeigt

### ISSUE THREAD

**Issue by Thomas9693** [Thomas9693/webcalendar#3]
Siehe Event Test - ueber mehrere Wochen

Start 02.02.2015
Ende: 25.02.2015

angezeigtes Ende: 04.02.

**Comment by TTDennis** [comment]
Dafür musst du mir aber die Events in der jeweiligen Woche übergeben

**Comment by Thomas9693** [comment]
Kann ich machen, kein Problem. Melde mich, wenn ich es erledigt habe.

----- Ursprüngliche Nachricht -----
Von: "TTDennis" <notifications@github.com>
Gesendet: ‎15.‎02.‎2015 11:49
An: "Thomas9693/webcalendar" <webcalendar@noreply.github.com>
Cc: "Thomas9693" <thomas9693@gmail.com>
Betreff: Re: [webcalendar] Events über mehrer Wochen werden nicht korrekt angezeigt (#3)

Dafür musst du mir aber die Events in der jeweiligen Woche übergeben

**Comment by Thomas9693** [comment]
Event-IDs werden nun übergeben

**Comment by TTDennis** [comment]
Endlich ... gefickst
